language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial

script:
  - cd backend/api-gateway
  - pip install masonite-cli
  - craft install
  - python -m pytest
